global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   transform_tolerance: 0.5
   static_map: true
   rolling_window: false

   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"} #static map
     - {name: laser_layer,             type: "costmap_2d::ObstacleLayer"} #laser use on walls and objects
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"} #inflation layer




